name: Release devtools image

on:
  push:
    branches:
    - master

  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo IMAGE_CREATED=$(date --utc +'%Y-%m-%dT%H:%M:%SZ') >> $GITHUB_ENV
    - uses: docker/setup-buildx-action@v3
    - uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - uses: docker/build-push-action@v5
      with:
        labels: |
          org.opencontainers.image.authors=Yang Sheng Han <progamesigner@gmail.com>
          org.opencontainers.image.created=${{ env.IMAGE_CREATED }}
          org.opencontainers.image.description=devtools
          org.opencontainers.image.documentation=https://github.com/${{ github.repository }}
          org.opencontainers.image.revision=${{ github.sha }}
          org.opencontainers.image.source=https://github.com/${{ github.repository }}
          org.opencontainers.image.title=devtools
          org.opencontainers.image.url=https://github.com/${{ github.repository }}
          org.opencontainers.image.vendor=https://github.com/${{ github.repository }}
          org.opencontainers.image.version=${{ github.sha }}
        push: true
        tags: ghcr.io/${{ github.repository }}:latest
